### ISSUE TITLE
Treasury Advisory Service Meeting -  Monday, 03th April, 2023

### ISSUE THREAD

**Issue by Andre-Diamond** [treasuryguild/Treasury-Advisory-Service#108]
## Attendees

- [x] Andre
- [x] Stephen
- [x] Miro

## Action Notes

- Don't close the issue after meeting as the GitHub action needs an _open issue_ with the label 'meeting' in order to make the new meeting issue.
- Keep notes in the body of each issue for these auto-generated meeting issues.

## Meeting Notes
- Issue with the GitHub Action that produces this meeting issue. Produces NULL result. Possible problem caused by lack of previous issue may resolve itself when the Action runs again for the next meeting. 
- This Issue appears to be resolved as the action has run as expected.
- This meeting's issue was null again, so need to find the problem and resolve.

- NULL result seems to be resolved ? Restarting this action may have caused the NULL character.
- Treasury Advisory Service should decide what updates go in the Meeting Notes body. 
- It could be useful for one participant to take notes in the meeting action body as a summary of what has been discussed in each task.
- Give some thought to formatting of this in 
- #64

**Comment by Andre-Diamond** [comment]
Previous in series: #107

**Comment by stephen-rowan** [comment]
This action did not run after 1st April 2023

**Comment by Andre-Diamond** [comment]
Next in series: #110
