### ISSUE TITLE
Automate, Educate, Communicate GitBook

### ISSUE THREAD

**Issue by stephen-rowan** [treasuryguild/Treasury-Advisory-Service#109]
Started work on reviewing and revising the Treasury Advisory GitBook in preparation for use as an end of proposal reference.

**Comment by stephen-rowan** [comment]
- Added GitHub CLI section https://quality-assurance-dao.gitbook.io/treasury-advisory-service/project-automation/general-introduction/github-cli

**Comment by Andre-Diamond** [comment]
What we've done
[] - [Close out report](https://creativecommons.org/licenses/by/4.0/)
[] -
[] -
