### ISSUE TITLE
Catalyst Training and Automation - Planning & Strategy Meeting 1st July 2022

### ISSUE THREAD

**Issue by stephen-rowan** [treasuryguild/Treasury-Advisory-Service#28]
NB : This is a draft Agenda for the planning meeting on July 1st 2022

Scope : F8 ABC of Governance & F8 Automate, Educate, Communicate
 
- [x] started work on dework integration
- [x] Agreed to integrate Training and Automation with Treasury Guild - with Felix and Stephen W as consultants
- [x] reach out to gimbalabs
- [x] Use dework to create bounties for F8 Automate - still document GitHub actions on GitBook
- [x] Use Canvas for F8 ABC of Governance

**Comment by whitevo** [comment]
Gimbals could be used as bounty rewards, adding weight to good work, or addition to already offered ADA.
Gimbalabs Tokenomics and Data Transparency group are working towards a consensus to make experiments cost-effective.

Fancy a change of name for this task?
**F8 Communicate, Atomate, Educate - Planning Meeting**
Starting any process with communication first looks like a safe play.

**Comment by Andre-Diamond** [comment]
Think we should def experiment with Gimbals in this project if we can. I'm pretty sure we can change the name as this was the name for the Proposal. The name for the Project currently is Catalyst Training and Automation. So for this task we can use 
**F8 Communicate, Automate, Educate - Planning Meeting** like you suggested @whitevo

**Comment by stephen-rowan** [comment]
Andre and me agree to use the name "Catalyst Training and Automation" for our project meetings

**Comment by stephen-rowan** [comment]
## Notes on Strategy

This meeting would discuss the basis of a general strategy for the  Catalyst Training and Automation community project. 
## Examples
- Who does what
- How are people rewarded
