### ISSUE TITLE
Document GitHub Open Source Strategy for Catalyst Projects

### ISSUE THREAD

**Issue by stephen-rowan** [treasuryguild/Treasury-Advisory-Service#35]
Develop and document a GitHub Open Source Strategy for Catalyst Projects as part of F8 Automate Open Source Project Standards.

**Comment by stephen-rowan** [comment]
Added @stephen-rowan as Treasury Guild Organization member in order to add and design Projects

**Comment by stephen-rowan** [comment]
## Potential Issues going forward

- [ ] Will clients have access to Project Board or just Treasury Guild
- [ ] What to do if they have their own Project system

**Comment by stephen-rowan** [comment]
Should Catalyst proposal texts be stored on a repo with a Open Source Licence

**Comment by stephen-rowan** [comment]
# Resolved Issues

- If the Client does not have an existing GitHub Org then we set one for them with a Co-ordination repo with a Project Board
- Agree OS licensing with them
- Archive the proposal text

**Comment by stephen-rowan** [comment]
Document this strategy in the Treasury Advisory Service GitBook
What Treasury Guild's approach to OS is
What this mean practically - licenses, repo location etc
Context - reference to Dirk and Fred's fireside chat - de-risking projects

An explainer for OS licences - Andre
How does OS effect collaboration and the culture of Catalyst

**Comment by Andre-Diamond** [comment]
Useful links 
- https://www.youtube.com/watch?v=OnmWFxlG2GA
 - https://www.youtube.com/watch?v=8nLfGcLXK3A
 - https://www.youtube.com/watch?v=UMIG4KnM8xw

**Comment by stephen-rowan** [comment]
Created page in Treasury Guild Advisory Service on Open Source Standards
https://quality-assurance-dao.gitbook.io/treasury-advisory-service/educational-materials/open-source-standards

**Comment by stephen-rowan** [comment]
- [ ] Produce material for GitBook [OS section](https://quality-assurance-dao.gitbook.io/treasury-advisory-service/educational-materials/open-source-standards)

**Comment by stephen-rowan** [comment]
- How will this material change given the governance changes of the last 3 months

**Comment by stephen-rowan** [comment]
Resume work on https://github.com/treasuryguild/Treasury-Advisory-Service/issues/35#issuecomment-1249360428

**Comment by stephen-rowan** [comment]
- [ ] Create F8 ABC of Governance content for this.

**Comment by stephen-rowan** [comment]
- Andre posted an OS Licence bot - https://ora.sh/environmental-beige-hdpf/open-source-license-bot
- Aiming for June 2023 to complete
