### ISSUE TITLE
Change of Scope for F8 Automate - How this works - project-automation/general-introduction/how-this-works

### ISSUE THREAD

**Issue by stephen-rowan** [treasuryguild/Treasury-Advisory-Service#38]
https://quality-assurance-dao.gitbook.io/treasury-advisory-service/project-automation/general-introduction/how-this-works

## How to describe our automate service ?

- How it works
- How to use it

**Comment by stephen-rowan** [comment]
"How this works" orginally related to GitHub Action bounty system. 
But we need to prepare a How this works for the Treasury Advisory Service

How to communicate the following -

We are developing an integrated 
- Treasury Guild system
- PM Automation - project boards, tasks, commitments, deliverables
- Reporting - how treasury and PM automation fits into monthly reporting
- Education - how to describe all the above as a service --> Clients

**Comment by stephen-rowan** [comment]
So we are dropping the bounty system and preparing an integrated system -

We are developing an integrated

- Treasury Guild system - Treasury dashboard automation
- PM Automation - Agenda automation, tracking issues, project board automation
- Reporting - how treasury and PM automation fits into monthly reporting - eg export PDF from automated dashboard
- Education - how to describe all the above as a service --> Clients - this is "How it works"

**Comment by stephen-rowan** [comment]
For monthly report August 24th "F8 Automate" -

# Change in scope
- We are dropping the bounty system and preparing an integrated reporting and PM system instead
# Progress
- Treasury Guild system - Treasury dashboard automation
- PM Automation - Agenda automation (tracking issues, project board automation)
# Planned
- Reporting - how treasury and PM automation fits into monthly reporting - eg export PDF from automated dashboard
- Education - how to describe all the above as a service --> Clients - this is "How it works"

**Comment by Andre-Diamond** [comment]
Removed Treasury dashboard automation
