### ISSUE TITLE
Automate GitBook Close Out (including Debrief of GitHub Actions)

### ISSUE THREAD

**Issue by stephen-rowan** [treasuryguild/Treasury-Advisory-Service#64]
An overview and discussion on Andre's work on GitHub Actions to date.
- https://quality-assurance-dao.gitbook.io/treasury-advisory-service/

## Discord Bot
https://github.com/treasuryguild/Community-Governance-Oversight/blob/main/.github/workflows/discord.yml

Runs after an issue is closed.

In body of issue is a JSON object
[Example](https://github.com/treasuryguild/Community-Governance-Oversight/issues/87)

## Agenda Issue

[Agenda Issue](https://github.com/CC-Treasury/issueblog/blob/main/.github/workflows/slides.yml)

**Comment by Andre-Diamond** [comment]
[Discord Bot](https://github.com/CC-Treasury/issueblog/blob/main/.github/workflows/Discord2.yml)
[Agenda Issue](https://github.com/CC-Treasury/issueblog/blob/main/.github/workflows/slides.yml)

**Comment by stephen-rowan** [comment]
Arrange debrief meeting 1st week of February 2023 - Stephen / Andre

**Comment by stephen-rowan** [comment]
Sent invite for GitHub Debrief meeting - 1400 UTC on 9th February 2023

## Draft Agenda

### Review Andre's Actions

- Run through the actions that process Treasury Advisory Service Meetings. 3 separate actions. 

## Priorities for learning 

- It would useful to do a refresher on the GitHub Action Tokens and Secrets.
- Stephen - Concentrate on Python Data Science, AI and GraphQL

**Comment by stephen-rowan** [comment]
Arranged another GitHub debrief meeting for 6th March 2023 to discuss Chat GPT

**Comment by stephen-rowan** [comment]
## Notes

GitHub API call example

https://api.github.com/repos/CC-Treasury/issueblog/issues/28 
https://api.github.com/repos/treasuryguild/Treasury-Advisory-Service/issues/28 

Access token

https://quality-assurance-dao.gitbook.io/treasury-advisory-service/project-automation/general-introduction/pat-token

**Comment by stephen-rowan** [comment]
Arrange a meeting on 10th April 2023 at 2pm BST between Andre & Stephen to review -

- GitHub Actions produced to date for F8 Automation
- Is it all complete and documented
- Does Stephen have an understanding of the work ?

**Comment by stephen-rowan** [comment]
## Meeting held on 17th April 2023

- Did not discuss GitHub Actions produced to date. But we did decide to categorize each GitBook content section with a Hint indicating authorship and funding.
- A lot of our work is documented but needs to be reorganized and merged in the GitBook. Particularly to act as a reference for closing reports.
- Possibility of discussing development work still on the table. Andre at present is manly using Javascript tools.

**Comment by stephen-rowan** [comment]
- Book meeting for 1st May 2023 to work on Automate GitBook, GitHub Action documentation
- Refine the Automate, Educate and Communicate Project

**Comment by stephen-rowan** [comment]
We had meeting to debrief and work on Automate GitBook. Andre
1 month needed for Automate closeout - Andre
Dework dashboard needs to be completed before Automate closeout - Andre 
Although we are aiming to close out - resources will still be used in other projects - Stephen

**Comment by Andre-Diamond** [comment]
Work completed on
Dework Performance Dashboard
Dework csv Exporter

**Comment by stephen-rowan** [comment]
## Meeting Note - Monday, 19th June 2023

Final F8 Proposal report and close out video drafted, submitted and accepted. @Andre-Diamond
